spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  kafka:
    bootstrap-servers: 192.168.1.101:9092
    producer:
      retries: 3  # 生产者发送失败时，重试次数
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 生产者消息key和消息value的序列化处理类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: tomge-consumer-group  # 默认消费者group id
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
redis:
  host: 192.168.1.101
  port: 6379
  password: Seeds123!

redisson:
  address: redis://${redis.host}:${redis.port}
  password: ${redis.password}
  timeout: 5000
  max-pool-size: 50
  min-idle-size: 25

ftp:
  hostname: 18.167.2.206
  username: seedsftp
  password: 1qaz@WSX
  port: 21
  basePath: /home/seedsftp

#file:
#  bucketName: seeds # 上文创建的桶名称
#  oss:
#    enable: true
#    endpoint: http://192.168.1.101:9000
#    access-key: seeds123!
#    secret-key: seeds123!

file:
  bucketName: apeastgame # 上文创建的桶名称
  oss:
    enable: true
    info: true
    endpoint: https://apeastgame.s3.ap-northeast-1.amazonaws.com
    access-key: AKIAQMKUPROLJREE5AGN
    secret-key: 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
  game:
    bucketName: apeastgame
    oss1:
      region: ap-northeast-1 #日本
      cdn: d3ox6c0xknt324.cloudfront.net
    oss2:
      region: eu-west-2 #欧洲
      cdn: dttqy0ok22fnz.cloudfront.net
    oss3:
      region: us-west-1 #美国
      cdn: derpo1ywdu54.cloudfront.net


email:
  enable: false
  host: email-smtp.ap-northeast-1.amazonaws.com
  from: seeds<no-reply-dev@theseeds.io>
  user: AKIAQMKUPROLIXMNEIJK
  pass: BBTyucDgyIg8qIDU1ki5XT1x3JEZZSA3cK1FC96TO0r4

login:
  twofa: true

zookeeper:
  address: 192.168.1.101:2181

service:
  url:
    uc: http://127.0.0.1:10101
    admin: http://127.0.0.1:10102
    account: http://127.0.0.1:10103
    wallet: http://127.0.0.1:10104
    notification: http://127.0.0.1:10105
    game: http://127.0.0.1:10106

# Springboot Actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: caches,health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
