spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrapAddress}
    consumer:
      group-id: ${spring.application.name}

feign:
  client:
    config:
      default:
        connect-timeout: 45000
        read-timeout: 45000
# elasticjob 配置
elasticjob:
  # zk地址，命名空间
  regCenter:
    serverLists: 192.168.1.101:2181
    namespace: seeds-account-job
  jobs:
    # 自动创建空闲地址，每分钟运行一次
    autoCreateAddressTask:
      # 作业job类
      elasticJobClass: com.seeds.account.task.AutoCreateAddressTask
      # 定时cron   every Minutes
      cron: "0 */1 * * * ?"
      # 作业分片总数
      shardingTotalCount: 1
      # 作业描述信息
      description: "自动创建空闲地址"
      #部署作业时，先禁止启动，部署结束后统一启动
      disabled: false
      #本地配置覆盖注册中心配置,每次启动作业都以本地配置为准
      overwrite: true
    # scanChainBlockJob
    scanChainBlockTask:
      elasticJobClass: com.seeds.account.task.ScanChainBlockTask
      cron: "0/5 * * * * ?"
      shardingTotalCount: 1
      description: "扫描新块"
      disabled: false
      overwrite: true
      # 执行提币请求，每5秒执行一次
    executeWithdrawTask:
      elasticJobClass: com.seeds.account.task.ExecuteWithdrawTask
      cron: "0/5 * * * * ?"
      shardingTotalCount: 1
      description: "执行提币请求"
      disabled: false
      overwrite: true
      # 查询提币结果，每5秒执行一次
    scanWithdrawTask:
      elasticJobClass: com.seeds.account.task.ScanWithdrawTask
      cron: "0/5 * * * * ?"
      shardingTotalCount: 1
      description: "查询提币结果"
      disabled: false
      overwrite: true
    # 扫描待归集地址余额 ，由于查询链上余额较慢， 地址较多。 这里15分钟执行一次
    scanPendingCollectBalancesTask:
      elasticJobClass: com.seeds.account.task.ScanPendingCollectBalancesTask
      cron: "* 0/15 * * * ?"
      shardingTotalCount: 1
      description: "扫描待归集地址余额"
      disabled: false
      overwrite: true