
spring:
  datasource:
    url: jdbc:mysql://192.168.6.101:3306/seeds_admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: i18n/messages

mybatis:
  type-aliases-package*: com.seeds.game.entity


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com.seeds.game.mapper/*Mapper.xml


springfox:
  documentation:
    swagger-ui:
      enabled: true

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

