
spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/seeds_game?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.game.entity


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    swagger-ui:
      enabled: true