spring:
  redis:
    host: redis.wpdbfj.ape1.cache.amazonaws.com
    port: 6379
    password: KtxCpkdSsIbm3uNx
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  kafka:
    bootstrap-servers: 10.18.14.26:9092
    producer:
      retries: 3  # 生产者发送失败时，重试次数
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 生产者消息key和消息value的序列化处理类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="seeds123";

    consumer:
      group-id: tomge-consumer-group  # 默认消费者group id
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="seeds123";

    appender:
      bootstrap:
        servers: 54.168.239.215:9092
        topic: applog
file:
  bucketName: seeds # 上文创建的桶名称
  oss:
    enable: true
    endpoint: https://theseeds.s3.ap-east-1.amazonaws.com
    access-key: AKIAQMKUPROLJREE5AGN
    secret-key: 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

email:
  enable: true
  host: email-smtp.ap-northeast-1.amazonaws.com
  from: seeds<no-reply@theseeds.io>
  user: AKIAQMKUPROLIXMNEIJK
  pass: BBTyucDgyIg8qIDU1ki5XT1x3JEZZSA3cK1FC96TO0r4

login:
  twofa: true
