spring:
  redis:
    host: Seeds-redis
    port: 6379
    password: Seeds123!

file:
  bucketName: seeds # 上文创建的桶名称
  oss:
    enable: true
    endpoint: http://192.168.1.101:9000
    access-key: seeds123!
    secret-key: seeds123!

email:
  host: smtp.gmail.com
  from: seeds<yangkang.duke@gmail.com>
  user: yangkang.duke@gmail.com
  pass: nfijtkbvgaflsprw