server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.cwvdyubg02yf.ap-east-1.rds.amazonaws.com:3306/seeds_uc?useUnicode=true&characterEncoding=utf-8
    username: seeds
    password: jT*kx9nqeqv6UQZR
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.uc.model

uc:
  sso:
    redis:
      keyExpireAfter: 259200


springfox:
  documentation:
    swagger-ui:
      enabled: true

redisson:
  address: redis://Seeds-redis:6379
  timeout: 5000
  poolsize: 50
  idlesize: 50
  password: Seeds123!


Seeds-admin: http://127.0.0.1:10102