server:
  port: 10103

spring:
  datasource:
    url: jdbc:mysql://Seeds-mysql:3306/seeds_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /


springfox:
  documentation:
    swagger-ui:
      enabled: true

redisson:
  address: redis://Seeds-redis:6379
  timeout: 5000
  poolsize: 50
  idlesize: 50
  password: Seeds123!

#
# wallet service
#
feign:
  client:
    config:
      default:
        connect-timeout: 45000
        read-timeout: 45000
  wallet:
    access:
      access-key: XXXXX
      secret-key: "5bb40a4623ead547e4b2f15awallet.wallet.secret"