server:
  port: 10104

spring:
  datasource:
    url: jdbc:mysql://Seeds-mysql:3306/seeds_wallet?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.uc.model


springfox:
  documentation:
    swagger-ui:
      enabled: true

redisson:
  address: redis://Seeds-redis:6379
  timeout: 5000
  poolsize: 50
  idlesize: 50
  password: Seeds123!

wallet:
  passwordKey: "5bb40a4623ead547e4b2f15awallet"
  chainId: 1
  access:
    allowed-timestamp-range: 10000
    key-list:
      - key: XXXXX
        secret: "5bb40a4623ead547e4b2f15awallet.access.key.secret"