server:
  port: 10100

spring:
  application:
    name: seeds-gateway

  cloud:
    gateway:
      routes:
        - id: seeds-uc-internal-service
          uri: http://127.0.0.1:10101/
          predicates:
            - Path=/uc-internal/**
          filters:
            - Auth
        - id: seeds-uc-open-service
          uri: http://127.0.0.1:10101/
          predicates:
            - Path=/uc-open/**

        - id: seeds-admin-public-service
          uri: http://127.0.0.1:10102/
          predicates:
            - Path=/admin-public/**
          filters:
            - AdminAuth
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
      default-filters:
        - StripPrefix=1
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Credentials, true
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@defaultResolver}'
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10

