server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AllenAi007/seeds-java.git #配置文件所在仓库
          username: 819628513@qq.com
          password: Mm135799876.
          default-label: main-dev #配置文件分支
          search-paths: config  #配置文件所在根目录

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}