spring:
  redis:
    host: 192.168.1.101
    port: 6379
    password: 123456

  cloud:
    gateway:
      routes:
        #- id: seeds-uc-public-service
        #uri: http://192.168.1.6:10103/
        #uri: http://localhost:10103/
        #predicates:
        #- Path=/uc-public/**
        - id: seeds-admin-public-service
          #uri: http://192.168.1.6:10105/
          uri: http://localhost:10105/
          predicates:
            - Path=/admin-public/**
          filters:
            - AdminAuth
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
      default-filters:
        - StripPrefix=1
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Credentials, true
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@defaultResolver}'
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
