spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: seeds-uc
          uri: http://192.168.1.6:10103/
          predicates:
            - Path=/seeds-uc/**
          filters:
            - SwaggerHeaderFilter
      loadbalancer:
        use404: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Credentials, true
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@defaultResolver}'
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
