#
#用户表
#
create table t_uc_user
(
    f_id           bigint(20) unsigned not null auto_increment comment 'Primary Key',
    f_password     varchar(200)        not null comment 'user password',
    f_state        smallint            not null comment '用户状态， 0-无效状态，1-正常，2-冻结，3-注销',
    f_type         smallint            not null comment '用户类型， 0-无效类型，1-普通用户',
    f_country_code varchar(20)         null comment '国家代码(手机用)',
    f_nationality  varchar(20)         not null comment '国籍(必选)',
    f_phone        varchar(50)         not null default '' comment '手机号, 全世界不会一样',
    f_email        varchar(50)         not null default '' comment '邮箱',
    f_ga_secret    varchar(200)        not null default '' comment 'ga 密钥',
    f_salt         varchar(50)         not null default '' comment '盐',
    f_updated_at   bigint(20)          not null default '0' comment 'update time',
    f_created_at   bigint(20)          not null default '0' comment 'create time',
    primary key (`f_id`),
    key idx_user_phone (f_phone),
    key idx_user_email (f_email)
) engine = InnoDB
  auto_increment = 10000000
  default charset = utf8mb4 comment 'user table';

# 国籍表
# 后面考虑要不要redis化
CREATE TABLE t_uc_country
(
    f_id         bigint(11) unsigned not null auto_increment comment '主键',
    f_area_code  varchar(50)         not null default '0' comment '地区代码',
    f_name_cn    varchar(100)        not null default '' comment '地区中文名称',
    f_name_en    varchar(100)        not null default '' comment '地区英文名称',
    f_created_at bigint(20)                   default '0' not null comment '创建时间',
    f_updated_at bigint(20)                   default '0' not null comment '操作时间',
    PRIMARY KEY (f_id),
    key idx_area_code (f_area_code)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = '国家列表';

# 用户kyc信息表
create table t_uc_kyc_detail
(
    f_id                 bigint(20) unsigned not null auto_increment comment '主键',
    f_uid                bigint(20) unsigned not null comment '所属的用户id',
    f_country_code       varchar(50)         not null comment '国家代码',
    f_first_name         varchar(200)        not null default '' comment '用户的名',
    f_last_name          varchar(200)        not null default '' comment '用户的姓',
    f_identity           varchar(200)        not null default '' comment '用户的证件-身份证，护照，或其他合法证件号',
    f_identity_file_uuid varchar(200)        not null comment '用户证件文件的uuid',
    f_created_at         bigint(20)          not null default '0' comment '创建时间',
    f_updated_at         bigint(20)          not null default '0' comment '操作时间',
    f_status             smallint            not null comment 'kyc状态 1待审核，2审核通过 3审核拒绝',
    f_comment            varchar(200)        not null comment '备注',
    f_operator_id        smallint            not null comment '审核人编号',
    f_operator_name      varchar(200)        not null comment '审核人姓名',
    primary key (f_id),
    key idx_kyc_identity (f_identity),
    key idx_kyc_uid (f_uid)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'kyc信息存储表';

# 附件表
CREATE TABLE t_uc_file
(
    f_id         bigint(20) unsigned not null auto_increment comment '主键',
    f_uid        bigint(20) unsigned not null comment '用户的id',
    f_uuid       varchar(200)        not null comment '文件的uuid',
    f_filename   varchar(200)        not null default '' comment '文件名',
    f_created_at bigint(20)          not null default 0 comment '创建时间',
    primary key (f_id),
    key idx_file_uid (f_uid),
    key idx_file_uuid (f_uuid)
) engine = InnoDB
  default charset = utf8mb4 COMMENT = '公共文件表';

#安全策略表
create table t_uc_security_strategy
(
    f_id         bigint(20) unsigned not null auto_increment comment '主键',
    f_uid        bigint(20) unsigned not null comment '用户的id',
    f_need_auth  tinyint             not null comment '是否开启了验证',
    f_auth_type  smallint            not null comment '验证的类型ClientAuthTypeEnum 1-phone, 2-email, 3-ga',
    f_created_at bigint(20)          not null default '0' comment '创建时间',
    f_updated_at bigint(20)          not null default '0' comment '操作时间',
    primary key (f_id),
    key idx_security_strategy_uid (f_uid)
) engine = InnoDB
  default charset = utf8mb4 COMMENT = '安全策略表';

# 后面考虑要不要redis化
create table t_uc_country_language
(
    f_id         bigint(20) unsigned not null auto_increment comment '主键',
    f_area_code  varchar(50)         not null comment '地区码',
    f_language   varchar(100)        not null comment '语言，如zh-cn',
    f_created_at bigint(20)          not null default '0' comment '创建时间',
    f_updated_at bigint(20)          not null default '0' comment '操作时间',
    primary key (f_id),
    unique key uniq_idx_area_code (f_area_code)
) engine = InnoDB
  default charset = utf8mb4 COMMENT = '国家或地区语言映射表';

insert into t_uc_country_language(f_area_code, f_language)
values ('0086', 'zh-cn')
;

insert into t_uc_country(f_area_code, f_name_cn, f_name_en)
values ('00355', '阿尔巴尼亚', 'Albania'),
       ('00213', '阿尔及利亚', 'Algeria'),
       ('00376', '安道尔共和国', 'Andorra'),
       ('00244', '安哥拉', 'Angola'),
       ('001264', '安圭拉岛', 'Anguilla'),
       ('001268', '安提瓜和巴布达', 'Antigua and Barbuda'),
       ('0054', '阿根廷', 'Argentina'),
       ('00374', '亚美尼亚', 'Armenia'),
       ('00297', '阿鲁巴', 'Aruba'),
       ('00247', '阿森松', 'Ascension'),
       ('0061', '澳大利亚', 'Australia'),
       ('00672', '澳大利亚海外领地', 'Australian overseas territories'),
       ('0043', '奥地利', 'Austria'),
       ('00994', '阿塞拜疆', 'Azerbaijan'),
       ('001242', '巴哈马', 'Bahamas'),
       ('00973', '巴林', 'Bahrain'),
       ('001246', '巴巴多斯', 'Barbados'),
       ('0032', '比利时', 'Belgium'),
       ('00501', '伯利兹', 'Belize'),
       ('00229', '贝宁', 'Benin'),
       ('001441', '百慕大群岛', 'Bermuda'),
       ('00975', '不丹', 'Bhutan'),
       ('00387', '波斯尼亚和黑塞哥维那', 'Bosnia and Herzegovina'),
       ('00267', '博茨瓦纳', 'Botswana'),
       ('0055', '巴西', 'Brazil'),
       ('001284', '英属维尔京群岛', 'British Virgin Islands'),
       ('00673', '文莱', 'Brunei'),
       ('00359', '保加利亚', 'Bulgaria'),
       ('00226', '布基纳法索', 'Burkina Faso'),
       ('00257', '布隆迪', 'Burundi'),
       ('00855', '柬埔寨', 'Cambodia'),
       ('001', '加拿大', 'Canada'),
       ('00238', '佛得角', 'Cape Verde'),
       ('001345', '开曼群岛', 'Cayman Islands.'),
       ('0056', '智利', 'Chile'),
       ('0086', '中国', 'China'),
       ('0057', '哥伦比亚', 'Colombia'),
       ('00269', '科摩罗群岛', 'Comoros Islands'),
       ('00682', '库克群岛', 'Cook Islands.'),
       ('00506', '哥斯达黎加', 'Costa Rica'),
       ('00385', '克罗地亚', 'Croatia'),
       ('00357', '塞浦路斯', 'Cyprus'),
       ('00420', '捷克', 'Czech Republic'),
       ('0045', '丹麦', 'Denmark'),
       ('00246', '迭戈加西亚群岛', 'Diego Garcia'),
       ('00253', '吉布提', 'Djibouti'),
       ('001809', '多米尼加共和国', 'Dominican Republic'),
       ('0020', '埃及', 'Egypt'),
       ('00503', '萨尔瓦多', 'El Salvador'),
       ('009714', '迪拜酋长国', 'Emirate of Dubai'),
       ('00372', '爱沙尼亚', 'Estonia'),
       ('00251', '埃塞俄比亚', 'Ethiopia'),
       ('00500', '福克兰群岛', 'Falkland Islands'),
       ('00298', '法罗群岛', 'Faroe Islands'),
       ('00679', '斐济', 'Fiji'),
       ('00358', '芬兰', 'Finland'),
       ('0033', '法国', 'France'),
       ('00594', '法属圭亚那', 'French Guiana'),
       ('00689', '法属玻利尼西亚', 'French Polynesia'),
       ('00241', '加蓬', 'Gabon'),
       ('00220', '冈比亚', 'Gambia'),
       ('00995', '格鲁吉亚', 'Georgia'),
       ('0049', '德国', 'Germany'),
       ('00233', '加纳', 'Ghana'),
       ('00350', '直布罗陀', 'Gibraltar'),
       ('0030', '希腊', 'Greece'),
       ('00299', '格陵兰岛', 'Greenland'),
       ('001473', '格林纳达', 'Grenada'),
       ('00590', '瓜德罗普', 'Guadeloupe'),
       ('001671', '关岛', 'Guam'),
       ('00502', '危地马拉', 'Guatemala'),
       ('00245', '几内亚比绍', 'Guinea-Bissau'),
       ('00592', '圭亚那', 'Guyana'),
       ('00509', '海地', 'Haiti'),
       ('00504', '洪都拉斯', 'Honduras'),
       ('00852', '中国香港', 'Hong Kong (China)'),
       ('0036', '匈牙利', 'Hungary'),
       ('00354', '冰岛', 'Iceland'),
       ('0091', '印度', 'India'),
       ('0062', '印度尼西亚', 'Indonesia'),
       ('00353', '爱尔兰', 'Ireland'),
       ('00972', '以色列', 'Israel'),
       ('0039', '意大利', 'Italy'),
       ('001876', '牙买加', 'Jamaica'),
       ('00962', '约旦', 'Jordan'),
       ('007', '哈萨克斯坦', 'Kazakhstan'),
       ('00254', '肯尼亚', 'Kenya'),
       ('00686', '基里巴斯', 'Kiribati'),
       ('0082', '韩国', 'Korea'),
       ('00965', '科威特', 'Kuwait'),
       ('00996', '吉尔吉斯坦', 'Kyrgyzstan'),
       ('00856', '老挝', 'Laos'),
       ('00371', '拉脱维亚', 'Latvia'),
       ('00266', '莱索托', 'Lesotho'),
       ('00423', '列支敦士登', 'Liechtenstein'),
       ('00370', '立陶宛', 'Lithuania'),
       ('00352', '卢森堡', 'Luxembourg'),
       ('00389', '马其顿', 'Macedonia'),
       ('00261', '马达加斯加', 'Madagascar'),
       ('00265', '马拉维', 'Malawi'),
       ('0060', '马来西亚', 'Malaysia'),
       ('00960', '马尔代夫', 'Maldives'),
       ('00223', '马里', 'Mali'),
       ('00356', '马耳他', 'Malta'),
       ('00223', '马里亚那群岛', 'Mariana Islands'),
       ('00692', '马绍尔群岛', 'Marshall Islands'),
       ('00596', '马提尼克', 'Martinique'),
       ('00222', '毛里塔尼亚', 'Mauritania'),
       ('00230', '毛里求斯', 'Mauritius'),
       ('0052', '墨西哥', 'Mexico'),
       ('00691', '密克罗尼西亚', 'Micronesia'),
       ('00373', '摩尔多瓦', 'Moldova'),
       ('00377', '摩纳哥', 'Monaco'),
       ('00976', '蒙古', 'Mongolia'),
       ('00382', '黑山', 'Montenegro'),
       ('001664', '蒙特塞拉特岛', 'Montserrat'),
       ('00212', '摩洛哥', 'Morocco'),
       ('00258', '莫桑比克', 'Mozambique'),
       ('00264', '纳米比亚', 'Namibia'),
       ('00674', '瑙鲁', 'Nauru'),
       ('00977', '尼泊尔', 'Nepal'),
       ('00599', '荷属安的列斯', 'Netheriands Antilles'),
       ('0031', '荷兰', 'Netherlands'),
       ('00687', '新喀里多尼亚', 'New Caledonia'),
       ('0064', '新西兰', 'New Zealand'),
       ('00505', '尼加拉瓜', 'Nicaragua'),
       ('00227', '尼日尔', 'Niger'),
       ('00234', '尼日利亚', 'Nigeria'),
       ('00683', '纽埃岛', 'Niue'),
       ('0047', '挪威', 'Norway'),
       ('00968', '阿曼', 'Oman'),
       ('00680', '帕劳', 'Palau'),
       ('00970', '巴勒斯坦', 'Palestine'),
       ('00507', '巴拿马', 'Panama'),
       ('00675', '巴布亚新几内亚', 'Papua New Guinea'),
       ('00595', '巴拉圭', 'Paraguay'),
       ('0051', '秘鲁', 'Peru'),
       ('0063', '菲律宾', 'Philippines'),
       ('0048', '波兰', 'Poland'),
       ('00351', '葡萄牙', 'Portugal'),
       ('001', '波多黎各', 'Puerto Rico'),
       ('00974', '卡塔尔', 'Qatar'),
       ('00262', '留尼旺', 'Reunion'),
       ('0040', '罗马尼亚', 'Romania'),
       ('007', '俄罗斯', 'Russia'),
       ('001758', '圣卢西亚', 'Saint Lucia'),
       ('00508', '圣皮埃尔和密克隆群岛', 'Saint Pierre and Miquelon'),
       ('001784', '圣文森特岛', 'Saint Vincent'),
       ('00684', '东萨摩亚(美)', 'Samoa Eastern'),
       ('00685', '西萨摩亚', 'Samoa Western'),
       ('00378', '圣马力诺', 'San Marino'),
       ('00239', '圣多美和普林西比', 'Sao Tome and Principe'),
       ('00966', '沙特阿拉伯', 'Saudi Arabia'),
       ('00221', '塞内加尔', 'Senegal'),
       ('00381', '塞尔维亚', 'Serbia'),
       ('00248', '塞舌尔', 'Seychelles'),
       ('00232', '塞拉利昂', 'Sierra Leone'),
       ('0065', '新加坡', 'Singapore'),
       ('00421', '斯洛伐克', 'Slovakia'),
       ('00386', '斯洛文尼亚', 'Slovenia'),
       ('00677', '所罗门群岛', 'Solomon Islands'),
       ('0027', '南非', 'South Africa'),
       ('0034', '西班牙', 'Spain'),
       ('0094', '斯里兰卡', 'Sri Lanka'),
       ('00290', '圣赫勒拿岛', 'St.Helena'),
       ('001758', '圣卢西亚', 'St.Lucia'),
       ('001784', '圣文森特', 'St.Vincent'),
       ('00597', '苏里南', 'Suriname'),
       ('00268', '斯威士兰', 'Swaziland'),
       ('0046', '瑞典', 'Sweden'),
       ('0041', '瑞士', 'Switzerland'),
       ('00886', '中国台湾', 'Taiwan (China)'),
       ('00992', '塔吉克斯坦', 'Tajikistan'),
       ('00255', '坦桑尼亚', 'Tanzania'),
       ('0066', '泰国', 'Thailand'),
       ('00228', '多哥', 'Togo'),
       ('00690', '托克劳群岛', 'Tokelau'),
       ('00676', '汤加', 'Tonga'),
       ('001868', '特立尼达和多巴哥', 'Trinidad and Tobago'),
       ('00216', '突尼斯', 'Tunisia'),
       ('0090', '土耳其', 'Turkey'),
       ('00993', '土库曼斯坦', 'Turkmenistan'),
       ('00688', '图瓦卢', 'Tuvalu'),
       ('00256', '乌干达', 'Uganda'),
       ('00380', '乌克兰', 'Ukraine'),
       ('00971', '阿拉伯联合酋长国', 'United Arab Emirates'),
       ('0044', '英国', 'United Kingdom'),
       ('00598', '乌拉圭', 'Uruguay'),
       ('00998', '乌兹别克斯坦', 'Uzbekistan'),
       ('00678', '瓦努阿图', 'Vanuatu'),
       ('00379', '梵蒂冈城', 'Vatican City'),
       ('0058', '委内瑞拉', 'Venezuela'),
       ('0084', '越南', 'Vietnam'),
       ('00681', '瓦利斯和富图纳', 'Wallis and Futuna'),
       ('00338', '南斯拉夫', 'Yugoslavia'),
       ('00243', '扎伊尔', 'Zaire'),
       ('00260', '赞比亚', 'Zambia');