package com.seeds.account.mapper;


import com.seeds.account.enums.ChainTxnDataAppType;
import com.seeds.account.model.ChainTxnData;

import java.util.List;

public interface ChainTxnDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chain_transaction_data
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chain_transaction_data
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    int insert(ChainTxnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chain_transaction_data
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    ChainTxnData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chain_transaction_data
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    List<ChainTxnData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chain_transaction_data
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    int updateByPrimaryKey(ChainTxnData record);

    ChainTxnData selectByAppTypeAndId(ChainTxnDataAppType appType, Long appId);
}