server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.cwvdyubg02yf.ap-east-1.rds.amazonaws.com:3306/seeds_uc?useUnicode=true&characterEncoding=utf-8
    username: seeds
    password: jT*kx9nqeqv6UQZR
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    appender:
      bootstrap:
        servers: 10.18.14.65:9092
        topic: applog-seeds

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.uc.model

uc:
  sso:
    redis:
      keyExpireAfter: 259200


springfox:
  documentation:
    swagger-ui:
      enabled: true

redisson:
  address: rediss://master.seeds-redis.wpdbfj.ape1.cache.amazonaws.com:6379
  password: KtxCpkdSsIbm3uNx
  timeout: 5000
  max-pool-size: 50
  min-idle-size: 25


Seeds-admin: http://127.0.0.1:10102