server:
  port: 10103

spring:
  datasource:
    url: jdbc:mysql://Seeds-mysql:3306/seeds_notification?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.notification.entity


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    swagger-ui:
      enabled: true

redisson:
  address: redis://Seeds-redis:6379
  timeout: 5000
  poolsize: 50
  idlesize: 50
  password: Seeds123!

webSocket:
  origin: *  #跨域设置
  port: 8899