spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seeds_dev
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

redisson:
  address: redis://localhost:6379
  timeout: 5000
  poolsize: 50
  idlesize: 50