server:
  port: 10103

spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.uc.model

uc:
  sso:
    redis:
      keyExpireAfter: 259200

# uc 文件存储目录
file:
  store:
    location: /seeds-uc/files/


