spring:
  datasource:
#    url: jdbc:mysql://192.168.1.101:3306/seeds_dev
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://192.168.1.101:3306/seeds_dev
    url: jdbc:mysql://192.168.1.101:3306/seeds_uc
    username: root
    password: 123456

redisson:
  address: redis://192.168.1.101:6379
#  address: redis://localhost:6379
  timeout: 5000
  poolsize: 50
  idlesize: 50
  password: 123456