spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  kafka:
    bootstrap-servers: 10.18.14.26:9092
    producer:
      retries: 3  # 生产者发送失败时，重试次数
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 生产者消息key和消息value的序列化处理类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: tomge-consumer-group  # 默认消费者group id
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

redis:
  host: "master.seeds-redis.wpdbfj.ape1.cache.amazonaws.com"
  port: 6379
  password: KtxCpkdSsIbm3uNx

redisson:
  address: rediss://${redis.host}:${redis.port}
  password: ${redis.password}
  timeout: 5000
  max-pool-size: 50
  min-idle-size: 25

file:
  bucketName: seeds # 上文创建的桶名称
  oss:
    enable: true
    endpoint: http://192.168.1.100:9000
    access-key: seeds123!
    secret-key: seeds123!
  game:
    access-key: AKIAQMKUPROLJREE5AGN
    secret-key: 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
    oss1:
      bucketName: apeastgame
      region: ap-northeast-1 #日本
      cdn: d3ox6c0xknt324.cloudfront.net
    oss2:
      bucketName: euwestgame
      region: eu-west-2 #欧洲
      cdn: dttqy0ok22fnz.cloudfront.net
    oss3:
      bucketName: uswestgame
      region: us-west-1 #美国
      cdn: derpo1ywdu54.cloudfront.net

email:
  enable: true
  host: email-smtp.ap-northeast-1.amazonaws.com
  from: seeds<no-reply@theseeds.io>
  user: AKIAQMKUPROLIXMNEIJK
  pass: BBTyucDgyIg8qIDU1ki5XT1x3JEZZSA3cK1FC96TO0r4

login:
  twofa: false

zookeeper:
  address: 10.18.14.26:2181

service:
  url:
    uc: http://seeds-uc.app.prd.devseeds.link
    admin: http://seeds-admin.app.prd.devseeds.link
    account: http://seeds-account.app.prd.devseeds.link
    wallet: http://seeds-wallet.app.prd.devseeds.link
    notification: http://seeds-notification.app.prd.devseeds.link
    game: http://seeds-game.app.prd.devseeds.link
    gateway: https://seeds-gateway.app.prd.devseeds.link
