
spring:
  datasource:
    url: jdbc:mysql://seeds-mysql.cwvdyubg02yf.ap-east-1.rds.amazonaws.com:3306/seeds_admin?useUnicode=true&characterEncoding=utf-8
    username: seeds
    password: jT*kx9nqeqv6UQZR
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  type-aliases-package*: com.seeds.game.entity


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    swagger-ui:
      enabled: true

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

