spring:
  datasource:
    url: jdbc:mysql://seeds-mysql.cwvdyubg02yf.ap-east-1.rds.amazonaws.com:3306/seeds_uc?useUnicode=true&characterEncoding=utf-8
    username: seeds
    password: jT*kx9nqeqv6UQZR
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.uc.model

uc:
  sso:
    redis:
      keyExpireAfter: 259200


springfox:
  documentation:
    swagger-ui:
      enabled: true


Seeds-admin: http://127.0.0.1:10102
Seeds-uc-logo-url: http://54.168.239.215:9999/admin/public/file/download/theseeds-uat?objectName=logo/f21f3996a8654073aa3739a3e46adb34.png