spring:
  redis:
    host: 54.168.239.215
    port: 6379
    password: Seeds123!
    timeout: 5000
    lettuce:
      pool:
        max-active: 32
        min-idle: 8
  cloud:
    gateway:
      routes:
        - id: seeds-uc-service
          uri: ${service.url.uc}
          predicates:
            - Path=/uc/**
          filters:
            - Auth
        - id: seeds-admin-service
          uri: http://Seeds-admin:10102
          predicates:
            - Path=/admin/**
          filters:
            - AdminAuth
        - id: seeds-wallet-service
          uri: http://Seeds-wallet:10104/
          predicates:
            - Path=/wallet/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
      default-filters:
        - StripPrefix=1
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Credentials, true
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RemoveResponseHeader=X-RateLimit-Remaining
        - RemoveResponseHeader=X-RateLimit-Replenish-Rate
        - RemoveResponseHeader=X-RateLimit-Requested-Tokens
        - RemoveResponseHeader=X-RateLimit-Burst-Capacity
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@defaultResolver}'
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10

