spring:
  datasource:
    url: jdbc:mysql://3.114.69.251:3306/seeds_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package*: com.seeds.account.model

account:
  zookeeper:
    #每次重试时间间隔，单位毫秒
    baseSleepTimeMs: 1000
    #重试次数
    maxRetries: 3
    #zookeeper服务连接id与端口
    connectString: ${zookeeper.address}
    #会话超时时间，单位毫秒
    sessionTimeoutMs: 5000
    #连接创建超时时间，单位毫秒
    connection-timeout-ms: 5000

feign:
  client:
    config:
      default:
        connect-timeout: 45000
        read-timeout: 45000
  wallet:
    access:
      access-key: XXXXX
      secret-key: "5bb40a4623ead547e4b2f15awallet.access.key.secret"


