package com.seeds.uc.model;

import com.seeds.common.enums.Language;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CountryLanguage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country_language.f_id
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country_language.f_area_code
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country_language.f_language
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    private Language language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country_language.f_created_at
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country_language.f_updated_at
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    private Long updatedAt;
}