package com.seeds.uc.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country.f_id
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country.f_area_code
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country.f_name_cn
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    private String nameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country.f_name_en
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country.f_created_at
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_country.f_updated_at
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    private Long updatedAt;
}