package com.seeds.uc.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_file.f_id
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_file.f_uid
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_file.f_uuid
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_file.f_filename
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_file.f_created_at
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    private Long createdAt;
}