package com.seeds.uc.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class KycDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_id
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_uid
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_country_code
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_first_name
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_last_name
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_identity
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_identity_file_uuid
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    //private String identityFileUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_created_at
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_kyc_detail.f_updated_at
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    private long updatedAt;

    /**
     * KYC状态
     */
    private int status;
    /**
     * 审核信息
     */
    private String comment;
    /**
     * 审核人编号
     */
    private long operatorId;
    /**
     * 审核人姓名
     */
    private String operatorName;

    /**
     * 身份文件
     */
    private File file;
}