package com.seeds.uc.model;

import com.seeds.uc.enums.ClientAuthTypeEnum;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class SecurityStrategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_security_strategy.f_id
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_security_strategy.f_uid
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_security_strategy.f_need_auth
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    private Boolean needAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_security_strategy.f_auth_type
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    private ClientAuthTypeEnum authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_security_strategy.f_created_at
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_security_strategy.f_updated_at
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    private Long updatedAt;
}