package com.seeds.uc.model;

import com.seeds.uc.enums.ClientStateEnum;
import com.seeds.uc.enums.ClientTypeEnum;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_id
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_password
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_state
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private ClientStateEnum state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_type
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private ClientTypeEnum type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_country_code
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private String countryCode;

    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_phone
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_email
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private String email;

    private String gaSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_salt
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_updated_at
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private Long updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_user.f_created_at
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    private Long createdAt;
}