spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  kafka:
    bootstrap-servers: 35.76.116.54:9092
    producer:
      retries: 3  # 生产者发送失败时，重试次数
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 生产者消息key和消息value的序列化处理类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="seeds123";
    consumer:
      group-id: tomge-consumer-group  # 默认消费者group id
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="seeds123";

redis:
  host: 35.76.116.54
  port: 6379
  password: Seeds123!

redisson:
  address: redis://${redis.host}:${redis.port}
  password: ${redis.password}
  timeout: 5000
  max-pool-size: 50
  min-idle-size: 25

ftp:
  hostname: 18.167.2.206
  username: seedsftp
  password: 1qaz@WSX
  port: 21
  basePath: /home/seedsftp

file:
  bucketName: seeds # 上文创建的桶名称
  oss:
    enable: true
    endpoint: http://35.76.116.54:9000
    access-key: seeds123!
    secret-key: seeds123!

email:
  enable: false
  host: email-smtp.ap-northeast-1.amazonaws.com
  from: seeds<no-reply-dev@theseeds.io>
  user: AKIAQMKUPROLIXMNEIJK
  pass: BBTyucDgyIg8qIDU1ki5XT1x3JEZZSA3cK1FC96TO0r4

zookeeper:
  address: 35.76.116.54:2181

login:
  twofa: true

service:
  url:
    uc: http://35.76.116.54:10101
    account: http://35.76.116.54:10103
    wallet: http://35.76.116.54:10104