spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  kafka:
    bootstrap-servers: 34.84.153.188:9092
    producer:
      retries: 3  # 生产者发送失败时，重试次数
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 生产者消息key和消息value的序列化处理类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: tomge-consumer-group  # 默认消费者group id
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

redis:
  host: 34.84.153.188
  port: 6379
  password: Seeds123!

redisson:
  address: redis://${redis.host}:${redis.port}
  password: ${redis.password}
  timeout: 5000
  max-pool-size: 50
  min-idle-size: 25

ftp:
  hostname: 18.167.2.206
  username: seedsftp
  password: 1qaz@WSX
  port: 21
  basePath: /home/seedsftp

file:
  bucketName: seeds # 上文创建的桶名称
  oss:
    enable: true
    endpoint: http://34.84.153.188:9000
    access-key: seeds123!
    secret-key: seeds123!
  game:
    access-key: AKIARE5ABL7ROKGNEWG4
    secret-key: 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
    oss1:
      bucketName: game1
      region: cn-northwest-1 #宁夏
      cdn: game1.s3.cn-northwest-1.amazonaws.com.cn
    oss2:
      bucketName: game2
      region: cn-north-1 #北京
      cdn: game2.s3.cn-north-1.amazonaws.com.cn
    oss3:
      bucketName: game3
      region: cn-north-1 #北京
      cdn: game3.s3.cn-north-1.amazonaws.com.cn
  metadata:
    bucketName: seedsnft
    endpoint: http://34.84.153.188:9000

email:
  enable: false
  host: email-smtp.ap-northeast-1.amazonaws.com
  from: seeds<no-reply-uat@theseeds.io>
  user: AKIAVHK56GXNBIIULDGW
  pass: BLz0TmjXCpgIrNSvgAIH4IZJWznP1yoEiJV5NTCeSVY2

zookeeper:
  address: 34.84.153.188:2181

login:
  twofa: false

service:
  url:
    uc: http://127.0.0.1:10101
    admin: http://127.0.0.1:10102
    account: http://127.0.0.1:10103
    wallet: http://127.0.0.1:10104
    notification: http://127.0.0.1:10105
    game: http://127.0.0.1:10106
    gateway: https://uat-gw.seedslabs.io
