spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrapAddress}
    consumer:
      group-id: ${spring.application.name}

feign:
  account:
    access:
      access-key: seeds-account-job
      secret-key: "xxx"
  client:
    config:
      default:
        connect-timeout: 45000
        read-timeout: 45000
# elasticjob 配置
elasticjob:
  # zk地址，命名空间
  regCenter:
    serverLists: 34.84.153.188:2181
    namespace: seeds-account-job
  jobs:
    # 自动创建空闲地址，每分钟运行一次
    createAddressJob:
      # 作业job类
      elasticJobClass: com.seeds.account.task.AutoCreateAddressTask
      # 定时cron   every Minutes
      cron: "0 */1 * * * ?"
      # 作业分片总数
      shardingTotalCount: 1
      # 作业描述信息
      description: "自动创建空闲地址"
      #部署作业时，先禁止启动，部署结束后统一启动
      disabled: false
      #本地配置覆盖注册中心配置,每次启动作业都以本地配置为准
      overwrite: true
    # scanChainBlockJob
    scanChainBlockJob:
      elasticJobClass: com.seeds.account.task.ScanChainBlockTask
      cron: "0/2 * * * * ?"
      shardingTotalCount: 1
      description: "scanChainBlockJob"
      disabled: false
      overwrite: true
      # 执行提币请求，每5秒执行一次
    executeWithdrawJob:
      elasticJobClass: com.seeds.account.task.ExecuteWithdrawTask
      cron: "0/5 * * * * ?"
      shardingTotalCount: 1
      description: "执行提币请求"
      disabled: false
      overwrite: true
      # 查询提币结果，每5秒执行一次
    scanWithdrawJob:
      elasticJobClass: com.seeds.account.task.ScanWithdrawTask
      cron: "0/5 * * * * ?"
      shardingTotalCount: 1
      description: "查询提币结果"
      disabled: false
      overwrite: true
    # 获取链上最新的gasPrice，并缓存到Redis
    gasPriceTask:
      elasticJobClass: com.seeds.account.task.GasPriceTask
      cron: "0/10 * * * * ?"
      shardingTotalCount: 1
      description: "获取链上最新的gasPrice"
      disabled: false
      overwrite: true
    # NFT的offer过期任务，每天3点执行一次
    nftOfferExpiredJob:
      elasticJobClass: com.seeds.account.task.NftOfferExpiredTask
      cron: "0 0 3 * * ?"
      shardingTotalCount: 1
      description: "NFT的offer过期任务"
      disabled: false
      overwrite: true
