spring:
  datasource:
    url: jdbc:mysql://35.76.116.54:3306/seeds_uc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Seeds123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /

mybatis:
  type-aliases-package*: com.seeds.uc.model

uc:
  sso:
    redis:
      keyExpireAfter: 259200


springfox:
  documentation:
    swagger-ui:
      enabled: true


Seeds-admin: http://127.0.0.1:10102
Use-invite-code-flag: false