package com.seeds.uc.mapper;

import com.seeds.uc.model.Country;

import java.util.List;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    Country selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country
     *
     * @mbg.generated Sun Aug 02 14:11:03 CST 2020
     */
    int updateByPrimaryKey(Country record);
}