package com.seeds.uc.mapper;

import com.seeds.uc.model.CountryLanguage;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CountryLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country_language
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country_language
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    int insert(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country_language
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    CountryLanguage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country_language
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    List<CountryLanguage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_country_language
     *
     * @mbg.generated Thu Sep 03 04:15:50 CST 2020
     */
    int updateByPrimaryKey(CountryLanguage record);

    CountryLanguage selectByCountryCode(@Param("countryCode") String countryCode);
}