package com.seeds.uc.mapper;

import com.seeds.uc.model.File;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_file
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_file
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_file
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    File selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_file
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    List<File> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_file
     *
     * @mbg.generated Tue Aug 25 19:51:07 CST 2020
     */
    int updateByPrimaryKey(File record);

    File selectByUuid(@Param("uuid") String uuid);
}