package com.seeds.uc.mapper;

import com.seeds.uc.model.KycDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KycDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_kyc_detail
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_kyc_detail
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    int insert(KycDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_kyc_detail
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    KycDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_kyc_detail
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    List<KycDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_kyc_detail
     *
     * @mbg.generated Tue Aug 25 20:06:57 CST 2020
     */
    int updateByPrimaryKey(KycDetail record);

    List<KycDetail> selectByUid(@Param("uid") Long uid);

    List<KycDetail> selectKycByPagination(@Param("currentPage") int currentPage, @Param("pageSize") int pageSize, int status);

    int updateKycStatus(KycDetail record);

    int countKycRecords(KycDetail record);

    KycDetail selectPassedKycDetailByUid(@Param("uid") Long uid);
}