package com.seeds.uc.mapper;

import com.seeds.uc.model.SecurityStrategy;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SecurityStrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_security_strategy
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_security_strategy
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    int insert(SecurityStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_security_strategy
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    SecurityStrategy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_security_strategy
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    List<SecurityStrategy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_security_strategy
     *
     * @mbg.generated Wed Aug 26 18:47:25 CST 2020
     */
    int updateByPrimaryKey(SecurityStrategy record);

    List<SecurityStrategy> listByUid(@Param("uid") Long uid);
}