package com.seeds.uc.mapper;

import com.seeds.uc.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated Sat Jul 25 12:20:31 CST 2020
     */
    int updateByPrimaryKey(User record);

    User selectByEmail(@Param("email") String email);

    User selectByPhone(@Param("phone") String phone);

    int countByEmail(@Param("email") String email);

    int countByPhone(@Param("phone") String phone);
}