package com.seeds.account.model;

import com.seeds.account.enums.ChainCommonStatus;
import com.seeds.account.enums.ChainTxnReplaceAppType;
import com.seeds.common.enums.Chain;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ChainTxnReplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_id
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_create_time
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_update_time
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_version
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_app_type
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private ChainTxnReplaceAppType appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_app_id
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_gas_price
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long gasPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_gas_limit
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long gasLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_gas_used
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long gasUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_tx_fee
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private BigDecimal txFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_block_number
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private Long blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_block_hash
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private String blockHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_tx_hash
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_nonce
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private String nonce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_replacement.f_status
     *
     * @mbg.generated Wed Jan 13 15:04:17 CST 2021
     */
    private ChainCommonStatus status;

    private String txValue;

    private Chain chain;
}