package com.seeds.account.model;

import com.seeds.account.enums.ChainTxnDataAppType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ChainTxnData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_id
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_create_time
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_update_time
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_version
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_app_type
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private ChainTxnDataAppType appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_app_id
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chain_transaction_data.f_data
     *
     * @mbg.generated Tue Jan 12 14:15:17 CST 2021
     */
    private String data;
}